### ISSUE TITLE
Very high CPU utilization on UpBoard

### ISSUE THREAD

**Issue by Gil401** [aws-robotics/kinesisvideo-encoder-ros1#15]
Hi Guys,

I am trying to run the encoder on a [UpBoard](https://up-board.org/up/specifications/)
I  have a camera connected via USB which I am trying to stream to my KVS.
The problem is that it takes a huge amount of my CPU power. is there something I can do in order to lower it?

Attaching a screenshot:
![Screenshot from 2019-05-12 14-36-50](https://user-images.githubusercontent.com/3350021/57581718-1b2f2f80-74c4-11e9-912f-1666e8a87e5f.png)

**Comment by mm318** [comment]
Hi,

We haven't worked with a UP Board before, but our guess is that the hardware acceleration available on the UP Board is Intel Quick Sync Video.

Assuming the FFmpeg suite is setup correctly on the UP Board operating system, can you try adding the setting `codec: "h264_qsv"` to your configuration YAML file (where other things like bitrate, FPS, etc. are set)? If it works, then you should expect to see "h264_qsv" where it currently says "libx264".

Please let us know how it goes.

**Comment by Gil401** [comment]
Hi @mm318 , Thanks for assisting with this.

I am getting
`[ERROR] [Initialize] h264_qsv codec not found!`

When running: `$ ffmpeg -encoders|grep qsv` I am getting:

> ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
>   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
>   configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
>   libavutil      54. 31.100 / 54. 31.100
>   libavcodec     56. 60.100 / 56. 60.100
>   libavformat    56. 40.101 / 56. 40.101
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 40.101 /  5. 40.101
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  2.101 /  1.  2.101
>   libpostproc    53.  3.100 / 53.  3.100
>

**Comment by mm318** [comment]
Hi @Gil401, your issue may be more suitable for the FFmpeg forums. Once you are able to achieve hardware accelerated encoding using FFmpeg on your Intel Atom based platform, we can try to help you configure this ROS node accordingly.

**Comment by Gil401** [comment]
So apparently this cpu does not support accelerated encoding.

Is there an alternative without using the h264 encoder?

**Comment by mm318** [comment]
To stream to Kinesis, it will need to be encoded in H.264 format (See "Q: What are the basic requirements to use the Kinesis Video Streams HLS APIs?" on the Kinesis Video [FAQs](https://aws.amazon.com/kinesis/video-streams/faqs/)).

The [datasheet for the Intel Atom x5 z8350](https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/atom-x5-processor-z8350-product-brief.pdf) leads us to to believe that it is capable of hardware-accelerated encoding, but we are unsure of how to leverage it on the software side.

**Comment by timrobotson** [comment]
Sorry we don't have the expertise to help you further with this. I've reached out to the Amazon Kinesis team to see if they've tested using this board before and if they'd be able to help.

**Comment by aaron-freshwater-aws** [comment]
Hi,

I am the engineering manager for Kinesis Video Streams.   We have not used this board before but have helped customers with similar issues on RPi.  Software based FFMPEG encoding will almost always put the CPU at 100% and fail to keep up with a medium or high definition stream.
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/158

Your board uses the Intel HD Graphics 400 which should support Quick Sync:
    https://www.techpowerup.com/gpu-specs/hd-graphics-400.c2906

You have to compile it into FFMPEG in order to enable hardware based acceleration:
    https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/quicksync-video-ffmpeg-install-valid.pdf

You should be able to diagnose this problem by working just with ffmpeg, as the CPU load happens before the video makes it to the KVS SDK.

**Comment by Gil401** [comment]
Hi @timrobotson and @aaron-freshwater-aws 

Thank you very much for assisting with this.

Currently I am unable to follow the tutorial since the link for Intel® Media Server Studio 2018 for Linux (which is a prerequisite) is invalid.

Is there a way to workaround it?

**Comment by nburek** [comment]
@Gil401 I'm not sure if their site was experiencing issues at the time, but the link https://software.intel.com/intel-media-server-studio seems to work for me.

**Comment by timrobotson** [comment]
@Gil401 I spoke to an engineer at up-board and although he wasn't sure what the issue could be he recommended posting on the [up community forums](https://forum.up-community.org/) if you haven't already to see if anyone there has an idea of what could be causing this.

**Comment by Gil401** [comment]
Hi @timrobotson 

Thanks again for assisting...

Will try to ask there... hope this is possible...

What is the CPU utilization of streaming to KVS on a Pi?

**Comment by ryanewel** [comment]
@Gil401 We have some performance metrics at the bottom of the README for the Kinesis Video Streamer node here https://github.com/aws-robotics/kinesisvideo-ros1. It looks like streaming to KVS averages about 15% CPU usage

**Comment by nburek** [comment]
Closing this issue out as the original question has been answered and it doesn't appear there is any further action to be taken for the kinesisvideo-encoder-ros1 package.
