### ISSUE TITLE
Missing license file in source

### ISSUE THREAD

**Issue by jamesiri** [aws-robotics/kinesisvideo-encoder-ros1#22]
In order to comply with the LGPLv2.1 you must provide the license with the source, not just a link. Failure to do so invalidates the license.

**Comment by raghaprasad** [comment]
We do provide an actual copy : https://github.com/aws-robotics/kinesisvideo-encoder-ros1/blob/master/h264_video_encoder/LICENSE.txt

Its inside the h264_video_encoder folder along with the actual code. 
This is the convention we have been using for all our other CEs and sample apps.
