### ISSUE TITLE
Carry the same same time-stamp header!!

### ISSUE THREAD

**Issue by JeyP4** [aws-robotics/kinesisvideo-encoder-ros1#35]
Hi
I am very happy with kind of work this node does. Its bandwidth requirement is almost half compare to MJPEG.

I was wondering how can see the time-stamp of the `kinesis_video_msgs` ?
And also
If this msg can contain processing time consumed in encoding, it would be a nice performance measurement tool. What do you say?

Thanks for consideration.

**Comment by AAlon** [comment]
> Hi
> I am very happy with kind of work this node does. Its bandwidth requirement is almost half compare to MJPEG.
> 
> I was wondering how can see the time-stamp of the `kinesis_video_msgs` ?
> And also
> If this msg can contain processing time consumed in encoding, it would be a nice performance measurement tool. What do you say?
> 
> Thanks for consideration.

What timestamp specifically are you looking for? The KinesisVideoFrame message contains fields such as decoding_ts and presentation_ts (microseconds): https://github.com/aws-robotics/kinesisvideo-ros1/blob/master/kinesis_video_msgs/msg/KinesisVideoFrame.msg#L4

As for the processing time spent encoding, it sounds like it would be a nice feature to add but we have no immediate plans for it; we'd greatly appreciate any contributions. Thanks!

**Comment by mm318** [comment]
Hi @JeyP4, hopefully your questions have been answered. Should you have new questions, please don't hesitate to open a new issue. Thanks!
