### ISSUE TITLE
How to subscribe to kinesis_video_msgs and display on screen? Decode?

### ISSUE THREAD

**Issue by JeyP4** [aws-robotics/kinesisvideo-encoder-ros1#36]
Hi

Can you please tell me, how can I subscribe and decode the image?

Thanks

**Comment by xabxx** [comment]
Hi there, kinesis_video_msg is not a topic and thus cannot be subscribed. Could you provide more details of what you are trying to do?

**Comment by JeyP4** [comment]
Thanx @xabxx for replying.

I understand that its a msg and the topic is `/video/encoded`.
I wanted to know, how can I decode 'kinesis_video_msg' and display the image.

If you can share any subscriber function, it would be very helpful.

Thanks

**Comment by timrobotson** [comment]
Sorry about the late response. This package is for subscribing to your existing camera node that is publishing images,  then it encodes the images, and delivers them to kinesis video. To pull that video from kinesis you'll need to [take a look at the Kinesis documentation](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/what-is-kinesis-video.html)

If you just want to subscribe to your robots camera and use the images without having to go through Kinesis here's how you can do that:

The way we decode and work with these images is using the ROS package [image_transport](http://wiki.ros.org/image_transport). You can see it used in our [Object Tracker Sample Application here](https://github.com/aws-robotics/aws-robomaker-sample-application-objecttracker/blob/cd3afdce15259812f2f4937d670559ae24017499/robot_ws/src/object_tracker_robot/launch/main.launch#L16). 

That image transport takes the encoded video from the camera and outputs it as a [sensor_msgs/Image](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Image.html) type. Your node can then [subscribe to this new topic and image type like so](https://github.com/aws-robotics/aws-robomaker-sample-application-objecttracker/blob/cd3afdce15259812f2f4937d670559ae24017499/simulation_ws/src/sagemaker_rl_agent/markov/environments/object_tracker_env.py#L72) and then you can save them out or display them as images using OpenCV by [following this tutorial](http://wiki.ros.org/cv_bridge/Tutorials/UsingCvBridgeToConvertBetweenROSImagesAndOpenCVImages)

Regards, Tim

**Comment by AAlon** [comment]
Closing, please reopen if you have any other related questions.
