### ISSUE TITLE
Does this support Intel QSV encoding

### ISSUE THREAD

**Issue by atyshka** [aws-robotics/kinesisvideo-encoder-ros1#53]
Pretty simple question: does this library provide support for Intel Quick Sync Video? If so, is it enabled by default or must it be configured?

**Comment by emersonknapp** [comment]
The repository does not support the QSV encoder - the only implementation is taking raw `sensor_msgs/Image` as input and outputting H264 encoded stream.

**Comment by atyshka** [comment]
No I’m aware of that, I’m referring to which implementation of h.264 encoding is used. Intel QSV is the hardware encoder for intel chips, the alternative is software encoding based on ffmpeg which will have worse performance

**Comment by emersonknapp** [comment]
Thank you for clarifying.

The h264 usage happens in `h264_encoder_core` - you can see in https://github.com/aws-robotics/kinesisvideo-encoder-common/blob/master/h264_encoder_core/package.xml that it explicitly depends on `ffmpeg`. I don't see this as being a hard requirement - but as you can see in https://github.com/aws-robotics/kinesisvideo-encoder-common/blob/2133bfc6847748e6cbda9c93919c3803b9086779/h264_encoder_core/src/h264_encoder.cpp#L27 - the `libavcodec` interfaces are used directly, so unless QSV provides those headers/APIs it does not seem trivial to drop it in as a replacement.
